export const acctAbi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'new_',
        type: 'address',
      },
      { indexed: false, internalType: 'bool', name: 'enabled', type: 'bool' },
    ],
    name: 'AuthsUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'module_',
        type: 'address',
      },
      { indexed: false, internalType: 'bytes4', name: 'sig_', type: 'bytes4' },
    ],
    name: 'ModuleAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'module_',
        type: 'address',
      },
      { indexed: false, internalType: 'bytes4', name: 'sig_', type: 'bytes4' },
    ],
    name: 'ModuleUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'new_',
        type: 'address',
      },
    ],
    name: 'OwnerUpdated',
    type: 'event',
  },
  { stateMutability: 'payable', type: 'fallback' },
  {
    inputs: [
      { internalType: 'address', name: 'to_', type: 'address' },
      { internalType: 'bytes', name: 'data_', type: 'bytes' },
    ],
    name: '_delegateCall',
    outputs: [{ internalType: 'bool', name: 'success', type: 'bool' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes4[]', name: 'sig_', type: 'bytes4[]' },
      { internalType: 'address', name: 'module_', type: 'address' },
    ],
    name: 'addModule',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'factory',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'sig_', type: 'bytes4' }],
    name: 'getModule',
    outputs: [{ internalType: 'address', name: 'module_', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'factory_', type: 'address' },
      { internalType: 'address', name: 'owner_', type: 'address' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'auth_', type: 'address' }],
    name: 'removeAuth',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newAuth_', type: 'address' }],
    name: 'setAuth',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner_', type: 'address' }],
    name: 'setOwner',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes4', name: 'sig_', type: 'bytes4' },
      { internalType: 'address', name: 'module_', type: 'address' },
    ],
    name: 'updateModule',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: 'contracts_', type: 'address[]' },
      { internalType: 'uint256[]', name: 'durations_', type: 'uint256[]' },
    ],
    name: 'whitelistContracts',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },

  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'tokenIn',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'tokenOut',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountIn',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountOut',
        type: 'uint256',
      },
    ],
    name: 'Swapped',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'tokenIn',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'tokenOut',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountIn',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountOut',
        type: 'uint256',
      },
    ],
    name: 'SwappedWith1Inch',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'tokenIn',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'tokenOut',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountIn',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountOut',
        type: 'uint256',
      },
    ],
    name: 'SwappedWithParaswap',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'tokenIn',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'tokenOut',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountIn',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountOut',
        type: 'uint256',
      },
    ],
    name: 'SwappedWithUniswap',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'tokenIn',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'tokenOut',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountIn',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountOut',
        type: 'uint256',
      },
    ],
    name: 'SwappedWithZeroX',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'decimalsIn_', type: 'uint256' },
      { internalType: 'uint256', name: 'decimalsOut_', type: 'uint256' },
      { internalType: 'uint256', name: 'amount_', type: 'uint256' },
      { internalType: 'uint256', name: 'unitAmt_', type: 'uint256' },
    ],
    name: 'calculateSlippage',
    outputs: [{ internalType: 'uint256', name: 'slippage_', type: 'uint256' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: 'dexs', type: 'uint256[]' },
      { internalType: 'address', name: 'tokenIn_', type: 'address' },
      { internalType: 'address', name: 'tokenOut_', type: 'address' },
      { internalType: 'uint256', name: 'amtIn_', type: 'uint256' },
      { internalType: 'uint256', name: 'unitAmt_', type: 'uint256' },
      { internalType: 'bytes', name: 'callData_', type: 'bytes' },
    ],
    name: 'swap',
    outputs: [{ internalType: 'uint256', name: 'amtOut_', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'tokenIn_', type: 'address' },
      { internalType: 'address', name: 'tokenOut_', type: 'address' },
      { internalType: 'uint256', name: 'amtIn_', type: 'uint256' },
      { internalType: 'uint256', name: 'unitAmt_', type: 'uint256' },
      { internalType: 'bytes', name: 'callData_', type: 'bytes' },
    ],
    name: 'swapWithOneInch',
    outputs: [
      { internalType: 'uint256', name: 'amtOut_', type: 'uint256' },
      { internalType: 'bool', name: 'success_', type: 'bool' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'tokenIn_', type: 'address' },
      { internalType: 'address', name: 'tokenOut_', type: 'address' },
      { internalType: 'uint256', name: 'amtIn_', type: 'uint256' },
      { internalType: 'uint256', name: 'unitAmt_', type: 'uint256' },
      { internalType: 'bytes', name: 'callData_', type: 'bytes' },
    ],
    name: 'swapWithParaswap',
    outputs: [
      { internalType: 'uint256', name: 'amtOut_', type: 'uint256' },
      { internalType: 'bool', name: 'success_', type: 'bool' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'tokenIn_', type: 'address' },
      { internalType: 'address', name: 'tokenOut_', type: 'address' },
      { internalType: 'uint256', name: 'amtIn_', type: 'uint256' },
      { internalType: 'uint256', name: 'unitAmt_', type: 'uint256' },
      { internalType: 'bytes', name: 'callData_', type: 'bytes' },
    ],
    name: 'swapWithUniswapV2',
    outputs: [
      { internalType: 'uint256', name: 'amtOut_', type: 'uint256' },
      { internalType: 'bool', name: 'success_', type: 'bool' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'tokenIn_', type: 'address' },
      { internalType: 'address', name: 'tokenOut_', type: 'address' },
      { internalType: 'uint256', name: 'amtIn_', type: 'uint256' },
      { internalType: 'uint256', name: 'unitAmt_', type: 'uint256' },
      { internalType: 'bytes', name: 'callData_', type: 'bytes' },
    ],
    name: 'swapWithZeroX',
    outputs: [
      { internalType: 'uint256', name: 'amtOut_', type: 'uint256' },
      { internalType: 'bool', name: 'success_', type: 'bool' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'to_',
        type: 'address',
      },
      { indexed: false, internalType: 'bytes', name: 'data_', type: 'bytes' },
    ],
    name: 'TransactionComplete',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address[]', name: '_address', type: 'address[]' },
      { internalType: 'bytes[]', name: '_data', type: 'bytes[]' },
    ],
    name: 'sendBatchedTransactions',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
